# Generated by Django 4.2 on 2024-11-22 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(default='Alex', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='name')),
                ('price_uan', models.FloatField(default=0, verbose_name='price_uan')),
                ('price_rub', models.FloatField(default=0, verbose_name='price_rub')),
                ('product_weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='weight')),
                ('product_quantity', models.IntegerField(default=0, verbose_name='quantity')),
                ('delivery_in_china_uan', models.FloatField(default=0, verbose_name='delivery_in_china_uan')),
                ('delivery_in_china_rub', models.FloatField(default=0, verbose_name='delivery_in_china_rub')),
                ('commission_uan', models.FloatField(verbose_name='commission_uan')),
                ('commission_rub', models.FloatField(verbose_name='commission_rub')),
                ('delivery_to_moscow', models.FloatField(default=0, verbose_name='delivery_to_moscow')),
                ('delivery_to_office', models.FloatField(default=0, verbose_name='delivery_to_office')),
                ('last_insurance', models.FloatField(default=0, verbose_name='last_insurance')),
                ('rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='reports.reports')),
            ],
        ),
    ]
