# Generated by Django 5.0.4 on 2024-06-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='name')),
                ('product_price', models.FloatField(default=0, verbose_name='price')),
                ('product_weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='weight')),
                ('product_quantity', models.IntegerField(default=0, verbose_name='quantity')),
                ('price_uan', models.FloatField(default=0)),
                ('total_price', models.FloatField(default=0)),
                ('commission', models.IntegerField(default=5)),
                ('delivery_to_moscow', models.FloatField(default=0)),
                ('delivery_to_office', models.FloatField(default=0)),
                ('last_insurance', models.FloatField(default=1)),
            ],
        ),
    ]
