# Generated by Django 5.0.4 on 2024-06-14 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_report_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='report',
            name='date',
        ),
        migrations.AddField(
            model_name='report',
            name='rep',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='reports.reports'),
        ),
    ]
