# Generated by Django 5.0.4 on 2024-06-14 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_reports_remove_report_date_report_rep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='rep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.reports'),
        ),
    ]
