# Generated by Django 5.0.4 on 2024-06-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_alter_report_rep'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='price_rub',
            field=models.FloatField(default=0),
        ),
    ]
