# Generated by Django 5.0.4 on 2024-06-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_report_price_rub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='product_price',
        ),
        migrations.AlterField(
            model_name='report',
            name='price_rub',
            field=models.FloatField(default=0, verbose_name='price_rub'),
        ),
        migrations.AlterField(
            model_name='report',
            name='price_uan',
            field=models.FloatField(default=0, verbose_name='price_uan'),
        ),
    ]
