# Generated by Django 5.0.4 on 2024-06-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_remove_report_product_price_alter_report_price_rub_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='total_price',
        ),
        migrations.AddField(
            model_name='report',
            name='delivery_in_china_rub',
            field=models.FloatField(default=0, verbose_name='delivery_in_china_rub'),
        ),
        migrations.AddField(
            model_name='report',
            name='delivery_in_china_uan',
            field=models.FloatField(default=0, verbose_name='delivery_in_china_uan'),
        ),
    ]
