# Generated by Django 5.0.4 on 2024-06-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_remove_report_commission_report_commission_rub_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='commission_rub',
            field=models.IntegerField(verbose_name='commission_rub'),
        ),
        migrations.AlterField(
            model_name='report',
            name='commission_uan',
            field=models.IntegerField(verbose_name='commission_uan'),
        ),
    ]
