# Generated by Django 5.0.4 on 2024-06-25 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('reports', '0013_alter_report_last_insurance'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='product_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.productcard'),
        ),
    ]
