# Generated by Django 5.0.4 on 2024-06-28 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0015_remove_report_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='delivery_to_moscow',
            field=models.FloatField(default=0, verbose_name='delivery_to_moscow'),
        ),
        migrations.AlterField(
            model_name='report',
            name='delivery_to_office',
            field=models.FloatField(default=0, verbose_name='delivery_to_office'),
        ),
        migrations.AlterField(
            model_name='report',
            name='rep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='reports.reports'),
        ),
    ]
