# Generated by Django 5.0.4 on 2024-06-12 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.TextField(max_length=200, verbose_name='Имя товара')),
                ('product_price', models.FloatField(verbose_name='Цена товара')),
                ('product_weight', models.FloatField(verbose_name='Вес товара')),
            ],
            options={
                'db_table': 'product_card',
            },
        ),
    ]
