# Generated by Django 4.2 on 2024-11-22 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.TextField(max_length=200, unique=True, verbose_name='Имя товара')),
                ('product_price', models.FloatField(verbose_name='Цена товара')),
                ('product_weight', models.FloatField(verbose_name='Вес товара')),
                ('delivery_in_china', models.FloatField(default=0, verbose_name='Доставка по Китаю')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'product_card',
            },
        ),
    ]
