# Generated by Django 5.0.4 on 2024-06-28 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcard',
            name='delivery_in_china',
            field=models.FloatField(default=0, verbose_name='Доставка по Китаю'),
        ),
    ]
