# Generated by Django 5.0.4 on 2024-07-12 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productcard_delivery_in_china'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcard',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
