# Generated by Django 5.0.4 on 2024-07-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_productcard_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcard',
            name='sku',
            field=models.IntegerField(default=0, verbose_name='id-товара'),
        ),
    ]
