# Generated by Django 5.0.4 on 2024-07-22 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productcard_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcard',
            name='sku',
        ),
        migrations.AlterField(
            model_name='productcard',
            name='product_name',
            field=models.TextField(max_length=200, unique=True, verbose_name='Имя товара'),
        ),
    ]
