# Generated by Django 4.2 on 2024-11-22 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField(blank=True, null=True)),
                ('wb_token', models.TextField(blank=True, null=True)),
                ('ozon_token', models.TextField(blank=True, null=True)),
                ('ozon_client_id', models.IntegerField(default=0, null=True)),
                ('tg_username', models.TextField(blank=True, null=True)),
                ('tg_first_name', models.TextField(blank=True, null=True)),
                ('tg_last_name', models.TextField(blank=True, null=True)),
                ('telegram_id', models.BigIntegerField(null=True, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
