# Generated by Django 4.2 on 2024-11-27 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0002_alter_profile_ozon_client_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ozon_client_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='ozon_token',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='wb_token',
        ),
    ]
