# Generated by Django 5.0.4 on 2024-07-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0003_alter_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ozon_token',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='wb_token',
            field=models.TextField(null=True),
        ),
    ]
