# Generated by Django 5.0.4 on 2024-07-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0004_alter_profile_email_alter_profile_ozon_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.TextField(null=True),
        ),
    ]
