# Generated by Django 5.0.4 on 2024-09-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0008_alter_profile_tg_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ozon_client_id',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
