# Generated by Django 4.2 on 2024-11-27 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopCard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('shop_name', models.TextField(max_length=200, unique=True, verbose_name='Название магазина')),
                ('shop_wb_token', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
                ('shop_ozon_token', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
                ('shop_ozon_client_id', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shop_card',
            },
        ),
    ]
