# Generated by Django 4.2 on 2024-11-24 22:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopCard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('shop_name', models.TextField(max_length=200, unique=True, verbose_name='Название магазина')),
                ('shop_wb_token', models.TextField(verbose_name='WB-token')),
                ('shop_ozon_token', models.TextField(verbose_name='OZON-token')),
                ('shop_ozon_client_id', models.TextField(default=0, verbose_name='OZON-client-id')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shop_card',
            },
        ),
    ]
