# Generated by Django 4.2 on 2024-11-24 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopcard',
            old_name='user_id',
            new_name='user',
        ),
    ]
